services:
  # 1. Database Service (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: smartshoe-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartshoe_db
    ports:
      - "5432:5432"
    volumes:
      # Jalankan inisialisasi skema (init.sql) lalu benih data (seed.sql) secara berurutan
      - ./database/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./database/seed/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - postgres_data:/var/lib/postgresql/data

  # 2. MQTT Broker Service (Eclipse Mosquitto)
  mqtt:
    image: eclipse-mosquitto:2
    container_name: smartshoe-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  # 3. Machine Learning Service (FastAPI)
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: smartshoe-ml-service
    restart: always
    ports:
      - "8000:8000"

  # 4. Gateway Service (Node.js)
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: smartshoe-gateway-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=smartshoe_db
      - MQTT_BROKER=mqtt://mqtt
      - MQTT_PORT=1883
      - MQTT_KEEPALIVE=60
      - ML_SERVICE_URL=http://ml-service:8000
      - SECRET_KEY=super_secret_session_key_for_smart_shoes
      - JWT_EXPIRES_IN=7d
    depends_on:
      - db
      - mqtt

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
